apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "shopping"
---
apiVersion: pekko.apache.org/v1
kind: PekkoMicroservice
metadata:
  name: shopping-order-service
  namespace: "shopping"
spec:
  replicas: 1
  image: <docker-registry>/shopping-order-service:<tag>
  javaOptions: "-Xlog:gc -XX:InitialRAMPercentage=75 -XX:MaxRAMPercentage=75"
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 512Mi
      cpu: 200m
