name: Link Validator

on:
  pull_request:
  schedule:
    - cron:  '0 6 * * 1-5'

jobs:
  validate-links:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # See https://github.com/actions/checkout/issues/299#issuecomment-677674415
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Run Antora
        run: make all

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Install Coursier command line tool
        run: curl -fLo cs https://git.io/coursier-cli-linux && chmod +x cs && ./cs

      - name: Run Link Validator
        run: ./cs launch net.runne::site-link-validator:0.2.2 -- scripts/validator.conf
